### ISSUE TITLE
Support Step 3.5 Flash model on MLX

### ISSUE THREAD

**Issue by Jbollenbacher** [lmstudio-ai/lmstudio-bug-tracker#1526]
The new model Step 3.5 Flash is currently not supported:

```
Failed to load model

Error when loading model: ValueError: Model type step3p5 not supported.
```

mlx-lm and mlx-engine allegedly now supports Step 3.5 Flash, but it still fails to load in LM-studio (see [this mlx-lm PR](https://github.com/ml-explore/mlx-lm/pull/836) and [this PR on mlx-engine](https://github.com/lmstudio-ai/mlx-engine/pull/273/changes#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552) which pulls in the new version of mlx-lm).

EDIT: Update, the error mode has now changed, but the model is still not working in the current builds (0.4.12)

**Comment by Jbollenbacher** [comment]
As of LM Studio 0.4.12 (Build 1), trying to load the step3p5 model on now gives the following error:

```
Failed to load model.

Error when loading model: AttributeError: 'PreTrainedConfig' object has no attribute 'max_position_embeddings'
```

This cryptic and unhelpful error actually means that the model_type=step3p5 in config.json is not being recongized as valid, so LMStudio is falling back to the default, PreTrainedConfig, which lacks the max_position_embeddings field and therefore fails to load.

So basically step3p5 is not still supported, but now with a new and less clear error.

**Comment by Jbollenbacher** [comment]
There is also some additional urgency to update this model, since Step-3.6 will be launching soon with similar architecture. Supporting step3.5 will make supporting 3.6 easier (perhaps trivial, if it's the same architecture exactly).

**Comment by neurlang** [comment]
please support model stepfun-ai/Step-3.5-Flash in LM studio.
what I can do to help progress this issue
