### ISSUE TITLE
[Bug] GLM-4.7-Flash MLX 6-bit fails with NameError/AttributeError on engine v1.6.0

### ISSUE THREAD

**Issue by nevetsyad** [lmstudio-ai/lmstudio-bug-tracker#1807]
## Environment

- **LM Studio version:** 0.4.11+1
- **MLX engine version:** 1.6.0 (`mlx-llm-mac-arm64-apple-metal-advsimd`)
- **macOS:** 26.4.1 (arm64, Apple Silicon, 64 GB unified memory)
- **Model:** `lmstudio-community/GLM-4.7-Flash-MLX-6bit` (safetensors, 5 shards)

## Description

After updating the MLX engine from v1.5.0 to v1.6.0, GLM-4.7-Flash MLX 6-bit fails to generate any tokens. The model loads successfully but errors out during inference with two distinct Python tracebacks:

**Error 1:**
```
Error in iterating prediction stream: NameError: name 'tree_reduce' is not defined
```

**Error 2:**
```
Error in iterating prediction stream: AttributeError: 'list' object has no attribute 'swapaxes'
```

Both errors occur at the MLX inference layer. The model worked correctly on engine v1.5.0. The update to v1.6.0 was done to enable Gemma 4 MLX support.

## Steps to Reproduce

1. Install MLX engine v1.6.0 in LM Studio 0.4.11
2. Load `lmstudio-community/GLM-4.7-Flash-MLX-6bit`
3. Send any chat completion request (via UI or API)
4. Observe inference failure

## Expected Behavior

GLM-4.7-Flash should generate tokens normally as it did on engine v1.5.0.

## Additional Context

- Rolling back to engine v1.5.0 resolves the issue for GLM but loses Gemma 4 MLX support.
- A simple curl test against `localhost:1234/v1/chat/completions` confirms the error is in the engine layer:
  ```json
  {"error":"Error in iterating prediction stream: NameError: name 'tree_reduce' is not defined"}
  ```
- Other MLX models (Gemma 4 26B) work correctly on v1.6.0.
- Other model formats (GGUF via llama.cpp backend) are unaffected.

## Possible Cause

The `tree_reduce` NameError suggests a missing import in the GLM model handler after the engine update. The `swapaxes` AttributeError may indicate a tensor shape handling regression in the GLM architecture path.

**Comment by tmhmac** [comment]
I've noticed a similar issue when running qwen3.6-35b-a3b-mlx 6bit (published by lmstudio-community). I receive the 'tree reduce' error for this model. 

Hardware:
Mac Studio M1 Max - 64 GB RAM

OS:
Tahoe 26.4.1

LM Studio:
* Version: 0.4.12 (Build 1)
* LM Studio MLX: v1.6.0
* Metal llama.cpp: v2.13.0
* Harmony (Mac): v0.3.5

**Comment by prem-arrcus** [comment]
I am also seeing this with model `Qwen3.6-35B-A3B-UD-MLX-4bit` with LM Studio `0.4.12+1` on Macbook Pro (M5 Pro) with 64GB RAM

**Comment by dontcrash** [comment]
There is this PR to fix it [here](https://github.com/ml-explore/mlx-lm/pull/1165/changes/2f04c833f4906d60de18dff128e274cd3936d8b4)
In the interim, you can patch this file yourself:

`~/.lmstudio/extensions/backends/vendor/_amphibian/app-mlx-generate-mac14-arm64@22/lib/python3.11/site-packages/mlx_lm/models/cache.py`

Before: `from mlx.utils import tree_flatten, tree_map, tree_unflatten`
After: `from mlx.utils import tree_flatten, tree_map, tree_reduce, tree_unflatten`

**Comment by prem-arrcus** [comment]
I am still getting this error even after making that change to `cache.py` and restarting lmstudio

```python
❯ grep 'from mlx.utils' ~/.lmstudio/extensions/backends/vendor/_amphibian/app-mlx-generate-mac14-arm64@22/lib/python3.11/site-packages/mlx_lm/models/cache.py
# from mlx.utils import tree_flatten, tree_map, tree_unflatten
from mlx.utils import tree_flatten, tree_map, tree_reduce, tree_unflatten
```

**Comment by prem-arrcus** [comment]
Sorry.. Ignore that. I had to apply that fix to this file too
`~/.lmstudio/extensions/backends/vendor/_amphibian/app-mlx-generate-mac26-arm64@21/lib/python3.11/site-packages/mlx_lm/models/cache.py`

**Comment by tmhmac** [comment]
> There is this PR to fix it [here](https://github.com/ml-explore/mlx-lm/pull/1165/changes/2f04c833f4906d60de18dff128e274cd3936d8b4) In the interim, you can patch this file yourself:
> 
> `~/.lmstudio/extensions/backends/vendor/_amphibian/app-mlx-generate-mac14-arm64@22/lib/python3.11/site-packages/mlx_lm/models/cache.py`
> 
> Before: `from mlx.utils import tree_flatten, tree_map, tree_unflatten` After: `from mlx.utils import tree_flatten, tree_map, tree_reduce, tree_unflatten`

Thanks for the PR link, this made the fix surgical. I was able to implement it and I've been giving the model some reps. Happy to report that I've not encountered the issue since manually updating cache.py. Thanks so much!

**Comment by savior714** [comment]
Date/time: 2026-04-24T00:22:03.792Z
Extension version: 3.52.1
Provider: openai (proxy)
Model: qwen3.6-27b-oq6

Error in iterating prediction stream: NameError: name 'tree_reduce' is not defined
