### ISSUE TITLE
Qwen3-Next not supported (please add)

### ISSUE THREAD

**Issue by aperepel** [lmstudio-ai/lmstudio-bug-tracker#999]
**Which version of LM Studio?**
Example: LM Studio 0.3.25 b2

**Which operating system?**
OSX

**What is the bug?**
`qwen3-next-80b-a3b-instruct-mlx` - unable to load the model, not supported error message for qwen3-next

**Screenshots**

**Logs**
```
🥲 Failed to load the model

Failed to load model

Error when loading model: ValueError: Model type qwen3_next not supported.
```

**To Reproduce**
1. Download the `qwen3-next-80b-a3b-instruct-mlx` model.
2. Load it in the chat.

**Comment by jjy1000** [comment]
```
🥲 加载模型失败

Failed to load model

Error when loading model: ValueError: Model type qwen3_next not supported.
```
同样的问题

**Comment by zereraz** [comment]
Version 0.3.25 (0.3.25)
model: Qwen3 Next 80B A3B Instruct


```
🥲 Failed to load the model

Failed to load model

Error when loading model: ValueError: Model type qwen3_next not supported.
```

**Comment by thusinh1969** [comment]
> Version 0.3.25 (0.3.25) model: Qwen3 Next 80B A3B Instruct
> 
> ```
> 🥲 Failed to load the model
> 
> Failed to load model
> 
> Error when loading model: ValueError: Model type qwen3_next not supported.
> ```

Same :(. ...!

**Comment by eAzhoujiajun** [comment]
同样问题，好像是mlx还未支持qwen3_next

**Comment by javi2375** [comment]
Same, not supported by current mlx-lm version in LMS

**Comment by mdoty4** [comment]
Same issue, no solution yet.

**Comment by MoAshour93** [comment]
Same issue here, I already tried multiple quantizations and multple versions of this model by different provides whether from Night Media or MLX community. The result is the same. I guess this MoE Qwen3 Next Architecture will be supported in another update in LM Studio. BTW, my update is on 13 Sep 2025.

**Comment by wuahe** [comment]
```
🥲 載入模型失敗

Failed to load model

Error when loading model: ValueError: Model type qwen3_next not supported.
```

**Comment by openSourcerer9000** [comment]
It should at least tell us before we DL it

**Comment by wangdong** [comment]
support it plz!

**Comment by brankoradovanovic-mcom** [comment]
The support for Qwen3-Next needs to land in llama.cpp first, see ggml-org/llama.cpp#15940.

**Comment by sammcj** [comment]
@brankoradovanovic-mcom llama.cpp does not provide MLX support, that is done by https://github.com/lmstudio-ai/mlx-engine

For everyone else - I'm willing to bet that all that's required is for LM Studio to bump the MLX version and cut a release, so I'm sure it won't be long - just remember it's the weekend so a lot of folks are probably busy with life things 😄

**Comment by ralphbutler** [comment]
Same problem ```
🥲 Failed to load the model

Failed to load model

Error when loading model: ValueError: Model type qwen3_next not supported.
```

**Comment by okrg** [comment]
Before any of this can happen, a new kernel must be developed by the heroes who manage mlx-ml; seems like they are on it
https://github.com/ml-explore/mlx-lm/pull/454

**Comment by yagil** [comment]
For Macs only: Qwen3-Next should work in LM Studio 0.3.26 + mlx-engine v0.26.1

https://lmstudio.ai/models/qwen/qwen3-next-80b

**Comment by wojo** [comment]
Indeed, 66 tok/sec on a M4 Max 64GB! Super impressive.

**Comment by ralphbutler** [comment]
Thank you very much !!

On Sep 15, 2025, at 8:51 PM, Yagil Burowski ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/3611042?s=20&v=4]yagil left a comment (lmstudio-ai/lmstudio-bug-tracker#999)<https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/999#issuecomment-3294553466>

For Macs only: Qwen3-Next should work in LM Studio 0.3.26 + mlx-engine v0.26.1

https://lmstudio.ai/models/qwen/qwen3-next-80b

**Comment by sammcj** [comment]
The latest release is noted as working, however loading any Qwen 3 next models with K/V cache quantisation errors with:

> `Error in iterating prediction stream: AttributeError: 'MambaCache' object has no attribute 'offset'`

The models do seem to load with full unquantised KV cache but that results in excessive memory usage.

- LM Studio 0.3.26 (Build 6)
- MLX Engine v0.27.0
- KVQ Q8_0

FYI @yagil

**Comment by wojo** [comment]
> The latest release is noted as working, however loading any Qwen 3 next models with K/V cache quantisation errors with:
> 
> > `Error in iterating prediction stream: AttributeError: 'MambaCache' object has no attribute 'offset'`
> 
> The models do seem to load with full unquantised KV cache but that results in excessive memory usage.
> 
> * LM Studio 0.3.26 (Build 6)
> * MLX Engine v0.27.0
> * KVQ Q8_0
> 
> FYI [@yagil](https://github.com/yagil)

Do you have KV cache quant on?

**Comment by yagil** [comment]
~~Please update to mlx-engine **0.26.1**, that's the earliest engine version with support~~

Edit: typo, 0.27.0 is the minimum version

**Comment by sammcj** [comment]
@wojo Yes.

@yagil 0.27.0 is newer than 0.26.1

<img width="565" height="116" alt="Image" src="https://github.com/user-attachments/assets/033f8f43-70b8-482a-8aa5-798fe68e594e" />

**Comment by yagil** [comment]
Sorry, I mixed up the versions. v0.27.0 is the minimum one.

Which quant are you using, and is it from lmstudio-community?

**Comment by wojo** [comment]
> [@wojo](https://github.com/wojo) Yes.
> 

Turn it off, I was able to replicate this issue with it on.

**Comment by sammcj** [comment]
@wojo Yes I'm aware, that's why I'm raising it as an issue as it should work (without it you'll use a lot of memory for the context).

@yagil I've tried both the recommended LM Studio model (top of the list at the moment) and the LM Studio Community (6bit) quant. Does it work for you (with qkv q8_0)?

**Comment by yagil** [comment]
> [@wojo](https://github.com/wojo) Yes I'm aware, that's why I'm raising it as an issue as it should work (without it you'll use a lot of memory for the context).
> 
> [@yagil](https://github.com/yagil) I've tried both the recommended LM Studio model (top of the list at the moment) and the LM Studio Community (6bit) quant. Does it work for you (with qkv q8_0)?

Ah I missed this part `The models do seem to load with full unquantised KV cache`. So this needs a separate bug report. If you will, please open one in: https://github.com/lmstudio-ai/mlx-engine/issues

**Comment by sammcj** [comment]
Done, thanks and sorry for polluting this issue!

https://github.com/lmstudio-ai/mlx-engine/issues/221

**Comment by aperepel** [comment]
Qwen3-next arch is now supported.
